# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
s1 = StudentProfile.create(user_id: "10000000001", status: "Active", firstname: "Tom", lastname: "Haythorn", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of Sydney", country: "Australia", city: "Sydney", state: "NSW", language: "English", gpa: 3.3, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 6, monthsspentabroadworking: 6, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Professional Services", hasworkexperiencein: "Legal", charitywork: "No", age: 25, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Male", currentlyemployed: "Yes", worktype: "Full-Time")
s2 = StudentProfile.create(user_id: "10000000002", status: "Active", firstname: "Blake", lastname: "Rowley", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of Melbourne", country: "Australia", city: "Melbourne", state: "VIC", language: "English", gpa: 4.0, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 6, monthsspentabroadworking: 6, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Professional Services", hasworkexperiencein: "Legal", charitywork: "No", age: 25, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Male", currentlyemployed: "Yes", worktype: "Full-Time")
s3 = StudentProfile.create(user_id: "10000000003", status: "Active", firstname: "Samantha", lastname: "Simmonds", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of Notre Dame Australia", country: "Australia", city: "Brisbane", state: "QLD", language: "English", gpa: 2.5, workexperience: 12, livingin: "Australia", monthsspentabroadliving: 0, monthsspentabroadworking: 0, degree: "UG - Bachelor", degreetype: "Geology", countryofdegree: "Australia", wantstoworkin: "Science", hasworkexperiencein: "Science", charitywork: "Yes", age: 27, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Female", currentlyemployed: "Yes", worktype: "Full-Time")
s4 = StudentProfile.create(user_id: "10000000004", status: "Active", firstname: "Manfred", lastname: "Williams", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of New South Wales", country: "Australia", city: "Perth", state: "WA", language: "English", gpa: 2.2, workexperience: 2, livingin: "Australia", monthsspentabroadliving: 0, monthsspentabroadworking: 0, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Information Technology", hasworkexperiencein: "Sales", charitywork: "No", age: 21, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Male", currentlyemployed: "Yes", worktype: "Full-Time")
s5 = StudentProfile.create(user_id: "10000000005", status: "Active", firstname: "Sarah", lastname: "Sarahson", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: "Maastrict University", country: "Netherlands", city: "Amsterdam", state: "NSW", language: "English", gpa: 1.3, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 6, monthsspentabroadworking: 24, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Netherlands", wantstoworkin: "Professional Services", hasworkexperiencein: "Legal", charitywork: "No", age: 22, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Female", currentlyemployed: "No", worktype: "Full-Time")
s6 = StudentProfile.create(user_id: "10000000006", status: "Active", firstname: "Hannah", lastname: "Fintech", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of New England", country: "Australia", city: "Sydney", state: "NSW", language: "English", gpa: 1.0, workexperience: 0, livingin: "Australia", monthsspentabroadliving: 0, monthsspentabroadworking: 0, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Marketing", hasworkexperiencein: "Legal", charitywork: "No", age: 25, permissiontoworkin: "Australia", referencesuponrequest: "No", gender:"Female", currentlyemployed: "No", worktype: "Full-Time")
s7 = StudentProfile.create(user_id: "10000000007", status: "Active", firstname: "Greg", lastname: "Older", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of South Austrailia", country: "Australia", city: "Adelaide", state: "SA", language: "English", gpa: 3.3, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 9, monthsspentabroadworking: 9, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Finance", hasworkexperiencein: "Finance", charitywork: "Yes", age: 20, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Male", currentlyemployed: "Yes", worktype: "Full-Time")
s8 = StudentProfile.create(user_id: "10000000008", status: "Active", firstname: "Ellen", lastname: "McDellen", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of Melbourne", country: "Australia", city: "Melbourne", state: "VIC", language: "English", gpa: 4.0, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 6, monthsspentabroadworking: 6, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Professional Services", hasworkexperiencein: "Legal", charitywork: "No", age: 25, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Female", currentlyemployed: "Yes", worktype: "Full-Time")
s9 = StudentProfile.create(user_id: "10000000009", status: "Active", firstname: "Dom", lastname: "Mcgone", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of Western Sydney", country: "Australia", city: "Sydney", state: "NSW", language: "English", gpa: 2.3, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 6, monthsspentabroadworking: 6, degree: "UG - Bachelor", degreetype: "Business", countryofdegree: "Australia", wantstoworkin: "Professional Services", hasworkexperiencein: "Legal", charitywork: "No", age: 25, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Male", currentlyemployed: "Yes", worktype: "Full-Time")
s10 = StudentProfile.create(user_id: "10000000010", status: "Active", firstname: "Willis", lastname: "Albertson", imagethumbnail: "http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/george-clooney.jpg", universityname: " University of Technology Sydney", country: "Australia", city: "Sydney", state: "NSW", language: "English", gpa: 3.0, workexperience: 24, livingin: "Australia", monthsspentabroadliving: 6, monthsspentabroadworking: 6, degree: "UG - Bachelor", degreetype: "Technology", countryofdegree: "Australia", wantstoworkin: "Professional Services", hasworkexperiencein: "Legal", charitywork: "No", age: 21, permissiontoworkin: "Australia", referencesuponrequest: "Yes", gender:"Male", currentlyemployed: "Yes", worktype: "Full-Time")

j3 = State.create(name: "QLD")
j4 = State.create(name: "VIC")
j5 = State.create(name: "NSW")
j6 = State.create(name: "SA")
j7 = State.create(name: "WA")
j8 = State.create(name: "NT")
j9 = State.create(name: "TAS")

City.create(name: 'Sydney', state: 'New South Wales')
City.create(name: 'Melbourne', state: 'Victoria')
City.create(name: 'Brisbane', state: 'Queensland')
City.create(name: 'Perth', state: 'Western Australia')
City.create(name: 'Adelaide', state: 'South Australia')
City.create(name: 'Gold Coast-Tweed Heads', state: 'Queensland/New South Wales')

